<h2 align="center">pandas</h2>

In [145]:
import pandas as pd

In [147]:
print(pd.__version__)

2.2.2

In [149]:
A=pd.Series([2,3,4,5],index=['a','b','c','d'])#you can specify index

In [151]:
A

a    2
b    3
c    4
d    5
dtype: int64

In [153]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [155]:
type(A.values)

numpy.ndarray

In [157]:
type(A)

pandas.core.series.Series

In [159]:
#we can also change get access of values as arrays or lists for ex:-
A['a']

2

In [161]:
A['a':'c']#final index is also included

a    2
b    3
c    4
dtype: int64

In [163]:
#convert dictonay into set
grades_dict={'a':4,'b':3.5,'c':3,'d':2.5}
grades=pd.Series(grades_dict)

In [165]:
print(grades.values)

[4.  3.5 3.  2.5]

In [167]:
print(grades.keys)

<bound method Series.keys of a    4.0
b    3.5
c    3.0
d    2.5
dtype: float64>

In [168]:
grades

a    4.0
b    3.5
c    3.0
d    2.5
dtype: float64

In [171]:
#to acccess
grades['a']

4.0

In [173]:
#can also be accessed by index for ex:-
grades[0:2]

a    4.0
b    3.5
dtype: float64

In [175]:
marks_dict={'a':85,'b':75,'c':65,'d':55,'e':45}
marks=pd.Series(marks_dict)

In [177]:
marks

a    85
b    75
c    65
d    55
e    45
dtype: int64

In [179]:
grades

a    4.0
b    3.5
c    3.0
d    2.5
dtype: float64

In [181]:
D=pd.DataFrame({'Marks':marks,'Grades':grades})

In [183]:
D

   Marks  Grades
a     85     4.0
b     75     3.5
c     65     3.0
d     55     2.5
e     45     NaN

In [185]:
#for transpose version
D.T

           a     b     c     d     e
Marks   85.0  75.0  65.0  55.0  45.0
Grades   4.0   3.5   3.0   2.5   NaN

In [187]:
#for access values of D
D.values
#returns two dimentional array

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5],
       [45. ,  nan]])

In [189]:
D.values[2,0]

65.0

In [191]:
D.values[2,:]

array([65.,  3.])

In [193]:
D.values[3,1]

2.5

In [195]:
#returns all colums
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [197]:
D.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [199]:
#to add new column
D['ScaledMarks']=100*(D['Marks']/90)#out od 90
D['new']=1

In [201]:
D

   Marks  Grades  ScaledMarks  new
a     85     4.0    94.444444    1
b     75     3.5    83.333333    1
c     65     3.0    72.222222    1
d     55     2.5    61.111111    1
e     45     NaN    50.000000    1

In [203]:
#to delete a column
del D['new']

In [205]:
D

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

##### masking

In [208]:
#for Ex:-
g=D[D['Marks']>70]

In [210]:
g

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333

In [212]:
#NAN ex:-
print(pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}]))

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [214]:
D

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [216]:
#to handle NAN you can use this fun which set fix value
D.fillna(0)

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     0.0    50.000000

In [218]:
D

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [220]:
##or you can drop that data

In [222]:
D.dropna()

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111

#### indexes

In [225]:
data=pd.Series(['a','b','c'],index=[1,3,5]) #provide explicit index

In [227]:
data[1] #explicit index
#use loc insted

'a'

In [229]:
#at index 1 will be printed
data[1:3] #implicit index 
#use iloc insted

3    b
5    c
dtype: object

In [231]:
data.loc[1:3] #will use explicit index which you provided

1    a
3    b
dtype: object

In [233]:
data.loc[1:]

1    a
3    b
5    c
dtype: object

In [235]:
data.iloc[1:3] #will use implicit index

3    b
5    c
dtype: object

In [237]:
D

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [239]:
D.iloc[2,:] #row at second index is c row

Marks          65.000000
Grades          3.000000
ScaledMarks    72.222222
Name: c, dtype: float64

In [241]:
D

   Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [243]:
D.iloc[1:3,0:2] # Slice rows 1 to 3 and columns A and B using iloc
#D.iloc[::-1,::-1] also can be reverced by this

   Marks  Grades
b     75     3.5
c     65     3.0

### intro to manipulate csv file data

In [246]:
import numpy as np
from sklearn.impute import SimpleImputer #to deal with empty data

In [248]:
df=pd.read_csv("")

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\DS\\project\\covid\\2019_nCoV_data.csv'

In [ ]:
df.head() #gives top records you specify in the parameter,by default it's 5

In [ ]:
print(df.columns)

In [ ]:
#don't run again after execute first time.it will give error
#because there won't be any colums you specified
df.drop(['Sno','Last Update'],axis=1,inplace=True)

if you don't write inplace=true then it will return on temporary varible
df will unchanged

In [ ]:
print(df.columns)

In [ ]:
df.head()

In [ ]:
#to rename columns
df.rename(columns={'Province/State':'Provance'})

it returned in temporary to store it use inplace=True

In [ ]:
df.head()

In [ ]:
df.rename(columns={'Province/State':'Provance'},inplace=True)

In [ ]:
df.head()

In [ ]:
#to convert date to pandas formate
df['Date'] = pd.to_datetime(df['Date'],errors='coerce')

# Create new columns for date and time
df['Only_Date'] = df['Date'].dt.date

errors='coerce' will convert invalid/malformed entries to NaT (Not a Time), so they won't break the code.

In [ ]:
df

In [ ]:
del df['Date']

In [ ]:
df.head()

In [ ]:
#to specify the order of column
df=df[['Only_Date','Provance','Country','Confirmed','Deaths','Recovered']]

In [ ]:
df.head()

In [ ]:
df.rename(columns={'Only_Date':'Date'},inplace=True)

In [ ]:
df.head()

In [ ]:
#to describe most of the statistics of the data
df.describe()

In [ ]:
a=df.describe()

In [ ]:
type(a)

In [ ]:
b=df.info()

In [ ]:
#there are null values at some feild
#to deal with it there are two ways 1 using simple imputer
#and 3 fillna
df=df.fillna('NA')

In [129]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df.head()

### groupby command

In [127]:
df2 = df.groupby('Country')[['Confirmed', 'Deaths', 'Recovered']].sum().reset_index()

NameError: name 'df' is not defined

In [125]:
df2

NameError: name 'df2' is not defined

In [ ]:
df2 = df.groupby(['Country','Date'])[['Confirmed', 'Deaths', 'Recovered']].sum().reset_index()

In [ ]:
df2

In [ ]:
df3=df2[df2['Confirmed']>100]

In [123]:
df3

NameError: name 'df3' is not defined